on: [push]

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get the two most recent tags
        run: |
          TAGS=$(git tag --sort=-creatordate | head -n 2)
          if [ "$(echo "$TAGS" | wc -l)" -lt 2 ]; then
            echo "Insufficient tags to calculate diff."
            exit 1
          fi
          TAG_OLD=$(echo "$TAGS" | tail -n 1)
          TAG_NEW=$(echo "$TAGS" | head -n 1)
          echo "tag_old=$TAG_OLD" >> $GITHUB_ENV
          echo "tag_new=$TAG_NEW" >> $GITHUB_ENV
      - name: Generate git diff
        run: |
          git diff ${{env.tag_old}} ${{env.tag_new}} changelogs/* > diff.txt
      - name: Prepare the Slack message
        run: |
          DIFF_CONTENT=$(head -n 100 diff.txt | sed 's/"/\\"/g')
          echo "slack_message=Latest tag ${{env.tag_new}}\n\n$DIFF_CONTENT"  >> $GITHUB_ENV
      - name: Post a message to Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{secrets.SUBMITTER_HELPDESK_SLACK_BOT_TOKEN}}
          payload: |
            channel: ${{secrets.TEST_CHANNEL_ID}}
            text: ${{env.slack_message}}
      - name: Debug Output
        run: |
          echo "Latest tag: ${{ env.tag_new }}"
          echo "Slack message: ${{ env.slack_message }}"
          
